language: R
sudo: false
cache: packages
script:
- Rscript -e "rmarkdown::render_site('.')"
- Rscript _commands/build-slides.R
- touch _site/.nojekyll
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_PAT
  local_dir: _site
  on:
    branch: master
